//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphDigitizer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphDigitizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Berlin Sans FB Demi;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green77\blue187;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sl240\slmult1\qc\cf1\lang10\b\f0\fs32\par
        ///\fs48 Graph Digitizer\cf0\b0\f1\fs22\par
        ///\par
        ///\fs28 Current Version: 1.0.1\par
        ///Date: \ltrmark 23/\ltrmark 06/\ltrmark 2019\par
        ///\par
        ///\b Author:\par
        ///\b0 Fernando Andreu\par
        ///fernando@andreu.info\par
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sl240\slmult1\qj\lang10\b\f0\fs22 Basic program usage:\b0\par
        ///\pard{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li720\sl240\slmult1\qj Load a graph with the first button of the above toolbar.\par
        ///{\pntext\f0 2.\tab}Select two points of the horizontal axis (X axis).\par
        ///{\pntext\f0 3.\tab}Select two points of the vertical axis ( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpGeneral {
            get {
                return ResourceManager.GetString("HelpGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg936\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f36\fbidi \fnil\fcharset134\fprq2{\*\panose 02010600030101010101}\&apos;b5\&apos;c8\&apos;cf\&apos;df{\*\falt DengXian};}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f050202020 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpGeneral_zh {
            get {
                return ResourceManager.GetString("HelpGeneral_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\lang10\f0\fs22 Press and hold the \b Left Control \b0 key over the main graph for enabling the \b precision mode\b0 .\par
        ///\par
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string HelpKeys {
            get {
                return ResourceManager.GetString("HelpKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg936\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f36\fbidi \fnil\fcharset134\fprq2{\*\panose 02010600030101010101}\&apos;b5\&apos;c8\&apos;cf\&apos;df{\*\falt DengXian};}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f050202020 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpKeys_zh {
            get {
                return ResourceManager.GetString("HelpKeys_zh", resourceCulture);
            }
        }
    }
}
